### ISSUE TITLE
Beancount org migration to-do

### ISSUE THREAD

**Issue by xuhcc** [beancount/docs#15]
- [x] Update repo url in documentation: https://docs.google.com/document/d/1Z37bQ45wDtjTPaMQ_x-f33p1trH9fNosEAUgbQXwp30/edit#heading=h.wcyqutvazcon
- [x] Update url in repo description.
- [x] Update [awesome-beancount](https://github.com/siddhantgoel/awesome-beancount/).
- [x] Update https://plaintextaccounting.org/#general-accounting

**Comment by xuhcc** [comment]
Done.
